version: '3.8'

services:
  db:
    image: postgres:15
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: notez
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    image: tosindotcom/notez_backend:0.2
    container_name: notez_backend
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/notez
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      NOTEZ_SECRET_KEY: a432rsKciXBO7aJm9jQ5laB75JcA/jjQsf90QFyrG8AUvnOzWKMULWPgAunmGhiGdv+qKUI+WOA/jSbCxJ48inHnLFnFa5z2RDYofN3IspncgBRztJDfODWet2VIZYYsrcHZ8v8xfcExtb2bxGfSrCs5Qneh5+zKFwkstwhfGIHPqum2EOoTDD8K4Iw1YmNvUh9SRG+t0zmV68jCFp0+nAFc1lcMp+GqSN7MabsieatBR5+/kZS8Q5WvamzhM1v9RLZ5RvHtkb1plkx5L3fPI3hYB5fOF50u4DvOQjx4dNBTSGSOx75/lmu8ffwlvSjFg/QYw5nROfWJ1dh0ar/krQXWXo6f0zMEWaA4Xu4bnk8=
    ports:
      - "8433:8433"

volumes:
  db_data: